import type { Metadata } from 'next'
import { SITE_URL } from '@/lib/seo'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import StarfieldCanvas from '@/components/starfield-canvas'

export const metadata: Metadata = {
  alternates: { canonical: `${SITE_URL}/terms-of-use` },
  robots: { index: true, follow: true },
  title: 'Terms of Use',
  description:
    "The Terms of Use governing access to and use of CosmicVend's website, operated by Hallow Essentials LLP.",
}

type Section = { title?: string; paras: string[] }

const INTRO: string[] = [
  'We, Hallow Essentials LLP, a limited liability partnership incorporated under the Limited Liability Partnership Act, 2008, bearing LLPIN: ACY-6204, having its registered office at 57/18, Sattanayakan Street, Tiruvannamalai, Tamil Nadu – 606601, represented by its Designated Partner, Mr. Arun N., operate our business under the brand name “CosmicVend” (hereinafter referred to as the “Company” or “CosmicVend”, as the context may require).',
  'These Terms of Use (“Terms”) govern your access to and use of the Company’s website available at https://www.cosmicvend.com, including all webpages, features, content, enquiry forms, and services made available through the Platform (collectively referred to as the “Platform”). References to the “Platform” in these Terms and all associated policies shall mean the website available at https://www.cosmicvend.com, including, without limitation, the About, Partner With Us, Guest Experience, Technology, Franchise, Venue Placement, Contact, and any other present or future webpages forming part of the website.',
  'The Company is engaged in operating a smart vending-based retail platform offering curated spiritual and wellness products through automated vending machines, while also facilitating venue placement partnerships, franchise opportunities, and related business enquiries through the Platform.',
  'These Terms represent the Company’s commitment to providing users with a transparent, secure, and informative online experience. By accessing, browsing, or using the Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms, together with our Privacy Policy and any other policies published on the Platform. If you do not agree with these Terms, you should refrain from accessing or using the Platform.',
  'Upon usage, registration, or even browsing through our Website creates a contractual relationship between you and us through this Terms of Use and other relevant policies associated with our Website, for all contractual, legal, and compliance purposes. This Terms of Use is considered as a legally binding agreement and is also considered as an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions about electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
]

const SECTIONS: Section[] = [
  {
    title: '1. DEFINITION AND INTERPRETATION',
    paras: [
      'a) Definition',
      '1.a.1. Applicable Laws - shall mean and refer to all the laws, rules, ordinances, by-laws, etc., and amendments thereafter, applicable within the territory of India.',
      '1.a.2. Content – shall mean and refer to all the text, advertisement, graphics, User interfaces, visual interfaces, photographs, trademarks, logos, brand names, descriptions, sounds, music, and artwork.',
      '1.a.3. Third Parties – shall mean and refer to all the legal entities either individual or entity linked on the Website apart from the Users and the creator of this Website.',
      '1.a.4. Service – shall mean the services made available through the Platform, including but not limited to providing information regarding CosmicVend’s business model, smart vending solutions, wellness products, venue placement opportunities, franchise opportunities, sustainability initiatives, guest experiences, technology, partnership enquiries, site walk requests, discovery calls, customer support, and such other services as may be introduced by the Company from time to time.',
      'b) Interpretation',
      '1.b.1. Company – “Company”, “We”, “Us”, or “Our” shall mean Hallow Essentials LLP, a limited liability partnership incorporated under the Limited Liability Partnership Act, 2008, bearing LLPIN ACY-6204, having its registered office at 57/18, Sattanayakan Street, Tiruvannamalai, Tamil Nadu – 606601, operating its business under the brand name “CosmicVend”, and shall include its designated partners, employees, representatives, affiliates, successors, and permitted assigns.',
      '1.b.2. Platform – shall mean the official website of CosmicVend accessible at https://www.cosmicvend.com, including all webpages, sub-pages, enquiry forms, features, functionality, content, and services made available through the website, whether existing now or introduced in the future.',
      '1.b.3. User - For the purposes of this Terms of Use, wherever the context so requires, “You”, “Your”, “Yourself”, “User”, and “Customer” shall mean and refer to natural and legal individuals who shall be users of this Website provided by Us and who is competent to enter into binding contracts, as per law.',
      '1.b.4. The headings of each section in these Terms of Use are only for the purpose of organizing the various provisions under these Terms of Use in an orderly manner and shall not be used by you to interpret the provisions contained herein in a manner as may apply to you. Further, it is specifically agreed by you that the headings shall not have legal or contractual value on your usage of the Website.',
      '1.b.5. The Parties shall refer and mean the company and User together, for the purpose of interpretation of terms of this Terms of Use.',
      '1.b.6. The use of this Website is solely governed by these Terms of Use, Privacy Policy, and any other relevant policies as updated on the Website and any modifications or amendments made thereto by us from time to time, at our sole discretion. If you as a User continue to access and use this Website, you are agreeing to comply with and be bound by the following Terms of Use, Privacy Policy, and any other applicable policies, thereof.',
      '1.b.7. You expressly agree and acknowledge that these Terms of Use and Privacy Policy, and any other applicable policies, are co-terminus in nature and that expiry/termination of either one will lead to the termination of the other.',
      '1.b.8. You unequivocally agree that these Terms of Use, Privacy Policy, and any other applicable policies, constitute a legally binding agreement between us and that you shall be subject to the rules, guidelines, policies, terms, and conditions applicable to your use of the Platform, and that the same shall be deemed to be incorporated into these Terms of Use and shall be treated as part and parcel of the same. You acknowledge and agree that no signature or express act is required to make these Terms of Use and the Privacy Policy binding on you and that your act of visiting/browsing any part of the Website constitutes your full and final acceptance of these Terms of Use, Privacy Policy, and any other applicable policies.',
      '1.b.9. We reserve the sole and exclusive right to amend or modify these Terms of Use without any prior permission or intimation to you, and you expressly agree that any such amendments or modifications shall come into effect immediately. If you do not adhere to the changes, you must stop using the Website at once. Your continued use of the Website will signify your acceptance of the changed Terms of Use.',
    ],
  },
  {
    title: '2. PLATFORM OVERVIEW',
    paras: [
      'a) Welcome to CosmicVend, the official online platform owned and operated by Hallow Essentials LLP (“Company”, “We”, “Us”, or “Our”). CosmicVend is a technology-enabled spiritual wellness brand that operates a smart vending-based retail ecosystem offering curated wellness and manifestation products through automated vending machines installed at selected commercial locations.',
      'b) The Platform has been developed to provide users with comprehensive information regarding the Company’s business, products, technology, sustainability initiatives, guest experience, venue placement programme, franchise opportunities, and other related offerings. It serves as an official communication channel through which prospective venue partners, franchise applicants, customers, investors, media representatives, vendors, and other stakeholders may learn about the Company’s services and submit enquiries or requests for further engagement.',
      'c) The Platform is intended solely to facilitate access to information regarding CosmicVend and to enable users to express interest in the Company’s products, services, partnerships, or business opportunities. Unless expressly stated otherwise, the Platform does not presently facilitate the direct online purchase of products, execution of franchise agreements, confirmation of venue placements, or completion of commercial transactions. Any commercial arrangement, including but not limited to venue placement, franchise appointment, product supply, licensing, or any other business relationship, shall become binding only upon the execution of separate written agreements between the Company and the concerned party.',
      'd) The Company reserves the right to modify, expand, suspend, withdraw, or discontinue any feature, functionality, content, service, or section of the Platform at any time without prior notice. The Company may also introduce additional digital services, customer accounts, loyalty programmes, online purchasing facilities, mobile applications, personalised wellness experiences, subscription services, or any other technology-enabled features in the future, all of which shall be governed by these Terms of Use unless separate terms and conditions are expressly notified.',
      'e) While the Company endeavours to ensure that the information available on the Platform is accurate, current, and complete, all content is provided for general informational purposes only and should not be construed as professional advice, a binding offer, a guarantee of availability, or a commitment by the Company. The Company reserves the right to revise, update, modify, or remove any information displayed on the Platform at its sole discretion.',
    ],
  },
  {
    title: '3. SERVICES ON THE PLATFORM',
    paras: [
      'a) The Platform provides a digital interface through which users may access information and interact with the Company in relation to its business operations and services. The services made available through the Platform include, without limitation, providing detailed information regarding CosmicVend’s smart vending solutions, curated spiritual and wellness offerings, manifestation themes, sustainability initiatives, vending technology, guest experience, venue placement programme, franchise opportunities, and other business initiatives undertaken by the Company from time to time.',
      'b) The Platform enables prospective venue partners, including hotels, airports, shopping malls, wellness centres, corporate establishments, and other eligible commercial spaces, to submit enquiries for the installation and operation of CosmicVend smart vending machines. Such enquiries may include requests for site evaluations, placement discussions, partnership proposals, or other preliminary commercial interactions. Submission of an enquiry through the Platform shall merely constitute an expression of interest and shall not create any legal obligation upon the Company to accept, approve, or proceed with such proposal.',
      'c) The Platform further facilitates franchise-related enquiries by allowing prospective entrepreneurs, investors, and business operators to express interest in acquiring franchise rights for the operation of CosmicVend vending machines within designated territories. The information made available on the Platform regarding franchise opportunities, indicative investment structures, projected business models, margins, territory rights, or operational support is provided solely for informational purposes. Any franchise relationship shall be subject to the Company’s internal evaluation process, territory availability, commercial negotiations, due diligence, execution of definitive franchise documentation, and compliance with all applicable legal and regulatory requirements.',
      'd) The Platform also functions as an official communication channel through which users may submit general enquiries, request discovery calls, schedule site visits, seek business information, subscribe to updates, or otherwise communicate with the Company regarding its products, services, partnerships, or business opportunities. The Company shall endeavour to respond to such communications within a reasonable period but does not warrant or guarantee that every enquiry will receive a response or result in a commercial engagement.',
      'e) Where applicable, the Platform may also provide access to educational content, promotional material, announcements, newsletters, sustainability initiatives, technology updates, digital wellness experiences, QR code-based affirmation journeys, or other informational resources intended to enhance user engagement and awareness of the CosmicVend brand.',
      'f) The Company reserves the absolute right to introduce, modify, expand, suspend, or discontinue any service, functionality, feature, or content available on the Platform at any time, with or without prior notice. The availability of any service on the Platform shall not be construed as an obligation on the part of the Company to continue offering such service indefinitely.',
      'g) Nothing contained on the Platform shall be construed as creating any partnership, agency, employment, joint venture, franchise, distributorship, investment opportunity, or other legally enforceable relationship between the Company and any user unless expressly agreed through a separate written agreement duly executed by the Company.',
      'h) Future Features: Any reference made on the Platform to future products, software, features, services, technological capabilities, digital experiences, or development roadmaps represents the Company’s present intentions only. Such references shall not constitute a contractual commitment or guarantee that any such feature will be developed, launched, or made available.',
    ],
  },
  {
    title: '4. COMPLIANCE',
    paras: [
      'a) This Terms of Use has been drafted and published in accordance with the applicable laws governing electronic records, electronic contracts, and information technology in India, including but not limited to the provisions of the Information Technology Act, 2000, the rules, regulations, notifications, and amendments issued thereunder from time to time, and all other Applicable Laws governing the operation and use of websites, digital platforms, electronic communications, and data protection.',
      'b) The Company publishes these Terms of Use to establish the terms governing access to and use of the Platform and to ensure transparency in its dealings with users, prospective venue partners, franchise applicants, customers, vendors, and other stakeholders accessing the Platform.',
      'c) Where the Company collects, processes, stores, or otherwise handles any personal information submitted by users through the Platform, such collection and processing shall be governed by the Company’s Privacy Policy and shall be undertaken in accordance with the applicable provisions of the Information Technology Act, 2000, the Digital Personal Data Protection Act, 2023, and any rules, regulations, or statutory modifications made thereunder from time to time, to the extent applicable.',
      'd) Nothing contained in these Terms of Use shall be construed as limiting or excluding the Company’s obligation to comply with any Applicable Laws, statutory requirements, governmental directions, or regulatory obligations that may become applicable to the operation of the Platform or the services offered by the Company from time to time.',
      'e) Users accessing or using the Platform acknowledge that they shall comply with all Applicable Laws while accessing, browsing, or interacting with the Platform and shall not engage in any activity that is unlawful, fraudulent, harmful, or otherwise prohibited under these Terms of Use or under Applicable Laws.',
    ],
  },
  {
    title: '5. ENQUIRIES AND USER INFORMATION',
    paras: [
      'a) The Platform enables users to communicate with the Company by submitting enquiries through the online enquiry forms made available on the Platform. In order to submit an enquiry, the User may be required to provide certain information, including but not limited to their Name, Company or Organisation (where applicable), Email Address, Phone Number, Enquiry Type, and Message, together with any other information that the Company may reasonably require to understand and respond to the enquiry.',
      'b) By submitting an enquiry through the Platform, the User represents and warrants that all information furnished is true, accurate, complete, current, and not misleading, and that the User has the lawful authority to provide such information. The User further undertakes to ensure that the information remains accurate and shall promptly notify the Company of any material changes, where applicable.',
      'c) The User acknowledges and agrees that the submission of an enquiry through the Platform constitutes only an expression of interest or a request for information and shall not be construed as creating any contractual obligation on the part of the Company. The Company reserves the absolute right, at its sole discretion, to accept, reject, defer, or decline to respond to any enquiry or request without assigning any reason and without incurring any liability whatsoever.',
      'd) The Company may use the contact information provided by the User to communicate with the User regarding the submitted enquiry, provide information relating to the Company’s products, services, venue placement opportunities, franchise programmes, business proposals, promotional communications (where consent has been provided), or for any other legitimate business purpose in accordance with the Company’s Privacy Policy and Applicable Laws.',
      'e) The Company reserves the right to verify the authenticity of any information submitted through the Platform and may refuse to process, respond to, or act upon any enquiry where the information provided is false, inaccurate, incomplete, misleading, fraudulent, or otherwise incapable of verification.',
      'f) The personal information submitted by the User through the enquiry form shall be collected, processed, stored, and used strictly in accordance with the Company’s Privacy Policy, which forms an integral part of these Terms of Use and is incorporated herein by reference.',
    ],
  },
  {
    title: '6. ELIGIBILITY',
    paras: [
      'a) You represent and warrant that you are competent and eligible to enter into legally binding agreements and of competent age and that you have the requisite authority to bind yourself/themselves to these Terms of Use as per the Applicable Law. However, if you are a minor using this Website, you may do so with the consent of your legal guardian. All Acts of the minor shall be deemed to be considered as the acts undertaken under the supervision of their legal guardian.',
      'b) You further represent that you will comply with these Terms of Use and all applicable local, state, national, and international laws, rules, and regulations.',
      'c) You shall not use the Website if you are not competent to enter into a contract or are disqualified from doing so by any other Applicable Laws, rule, or regulation, currently in force.',
    ],
  },
  {
    title: '7. CONTENT',
    paras: [
      '7.1. General',
      'a) All Content available on the Platform, including but not limited to text, articles, descriptions, graphics, photographs, illustrations, videos, audio recordings, animations, logos, trademarks, trade names, service marks, icons, layouts, colour schemes, software, user interfaces, visual interfaces, website design, business information, marketing materials, product descriptions, manifestation themes, technology descriptions, sustainability initiatives, and all other materials displayed on or made available through the Platform (collectively, the “Content”), is either owned by, licensed to, or lawfully used by the Company and is protected under the Applicable Laws relating to intellectual property, including copyright, trademark, and other proprietary rights.',
      'b) While the Company endeavours to ensure that the information and Content made available on the Platform is accurate, complete, and up to date, such Content is provided solely for general informational purposes. The Company does not warrant or guarantee that the Content will always be accurate, complete, current, uninterrupted, or free from errors or omissions and reserves the right to modify, update, replace, or remove any Content at any time without prior notice.',
      'c) The Platform may contain references to third-party technologies, software providers, payment gateways, communication services, cloud service providers, analytics providers, maps, QR code services, or other third-party services.',
      'd) The Company neither controls nor endorses such third-party services and shall not be responsible for their availability, functionality, security, or content.',
      '7.2. Ownership of Content',
      'a) Unless expressly stated otherwise, all intellectual property rights, title, and interest in and to the Platform and its Content shall remain the exclusive property of the Company or its respective licensors. Nothing contained on the Platform shall be construed as granting, whether expressly, impliedly, or otherwise, any licence or right to use any trademark, copyright, trade dress, design, logo, domain name, proprietary information, or other intellectual property belonging to the Company without its prior written consent.',
      'b) No Content appearing on the Platform may be copied, reproduced, republished, uploaded, transmitted, displayed, translated, adapted, modified, distributed, sold, licensed, exploited, or otherwise used, in whole or in part, for any commercial or non-commercial purpose without the prior written permission of the Company or the applicable intellectual property owner, except as expressly permitted under Applicable Laws.',
      '7.3. User-Submitted Information',
      'a) The Platform may permit Users to submit enquiries, messages, applications, or other communications through online forms or other designated communication channels. The User represents and warrants that all information, documents, and materials submitted to the Company are true, accurate, complete, lawful, and do not infringe the intellectual property rights, privacy rights, or any other legal rights of any third party.',
      'b) The User shall not submit or transmit through the Platform any information or material that is false, misleading, fraudulent, defamatory, obscene, offensive, unlawful, abusive, harmful, or otherwise in violation of these Terms of Use or any Applicable Laws. The Company reserves the right, at its sole discretion, to refuse, disregard, remove, or take appropriate action with respect to any such submission and may report the matter to the appropriate authorities where required under Applicable Laws.',
      'c) The User shall remain solely responsible for the information submitted through the Platform and agrees to indemnify and hold harmless the Company against any claims, losses, liabilities, damages, costs, or expenses arising out of or relating to such submission.',
      'd) User Feedback: Any feedback, suggestions, proposals, ideas, comments, recommendations, or improvements voluntarily submitted to the Company shall be deemed non-confidential and non-proprietary unless otherwise expressly agreed in writing. The Company shall be entitled to use, modify, reproduce, implement, publish, or otherwise exploit such feedback without any obligation to compensate the User.',
      '7.4. Limited Licence',
      'a) Subject to compliance with these Terms of Use, the Company grants the User a limited, personal, non-exclusive, non-transferable, non-sublicensable, and revocable licence to access and use the Platform solely for lawful, personal, informational, or legitimate business purposes. This licence does not transfer any ownership or intellectual property rights in the Platform or its Content.',
      'b) Except to the extent expressly permitted by Applicable Laws or with the Company’s prior written consent, the User shall not copy, reproduce, modify, create derivative works from, reverse engineer, decompile, distribute, publish, display, commercially exploit, or otherwise use any part of the Platform or its Content in any manner whatsoever.',
    ],
  },
  {
    title: '8. NO FRANCHISE OFFER OR INVESTMENT SOLICITATION',
    paras: [
      'The information made available on the Platform regarding franchise opportunities, territory availability, investment structures, machine packages, indicative margins, royalty structures, revenue sharing, commercial models, business projections, or other related information is intended solely for general informational purposes and preliminary discussions.',
      'Nothing contained on the Platform shall constitute:',
      'a) an offer capable of acceptance;',
      'b) an invitation to invest;',
      'c) a solicitation of investment;',
      'd) a public offer;',
      'e) a franchise grant;',
      'f) a legally binding proposal; or',
      'g) any guarantee that a franchise, territory, venue placement, distributorship, or business opportunity will be offered.',
      'Any franchise, venue placement, distributorship, or other commercial relationship shall arise only upon execution of definitive written agreements by the Company.',
    ],
  },
  {
    title: '9. NO EARNINGS REPRESENTATION',
    paras: [
      'a) The Company makes no representation or warranty regarding any revenue, profitability, return on investment, sales volume, business success, occupancy, customer traffic, or commercial performance.',
      'b) Any financial illustrations, projections, examples, margins, or business models displayed on the Platform are indicative only and shall not be construed as guarantees of future performance.',
      'c) Business performance depends upon several factors including market conditions, operational efficiency, consumer demand, location, regulatory requirements, competition, and other factors beyond the Company’s control.',
    ],
  },
  {
    title: '10. INDEMNITY',
    paras: [
      'You agree to indemnify, defend and hold harmless the Company, and its respective directors, officers, employees, and agents (hereinafter collectively referred to as “Parties”), from and against any losses, liabilities, claims, damages, demands, costs, and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by us that arise out of, result from, or maybe payable by, any breach or non-performance of any representation, warranty, covenant, or agreement made or obligation to be performed according to these Terms of Use. Further, you agree to hold the Company harmless against any claims made by any Third Party due to/ or arising out of, or in connection with:',
      'a) Your use of the Website;',
      'b) Your violation of these Terms of Use;',
      'c) Your violation of any rights of another Parties, Users, and/or Third-Party;',
      'd) Your alleged improper conduct according to these Terms of Use; and',
      'e) Your conduct in connection with the Website.',
      'You agree to fully cooperate in indemnifying the Company at your own expense. You also agree not to settle with any party without the consent of the Company.',
      'In no event shall we be liable to compensate you or any Third Party for any special, incidental, indirect, consequential, or punitive damages whatsoever, including those resulting from loss of use, data, or profits, whether or not foreseeable, and whether or not you had been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence, or other tortuous action, or any other claim arising out of or in connection with your use of, or access, or availing Services from or materials contained therein on the Website.',
    ],
  },
  {
    title: '11. LIMITATION OF LIABILITY',
    paras: [
      '11.1. We are not responsible for any consequences arising out of the following events:',
      '11.1.1. if the Website is inoperative/non-responsive due to any connectivity errors associated with the internet connection such as but not limited to slow connectivity, no connectivity, server failure;',
      '11.1.2. if you have fed incorrect information or data or for any deletion of data;',
      '11.1.3. if there is an undue delay or inability to communicate through email;',
      '11.1.4. if there is any deficiency or defect in the Services managed by the Company; and',
      '11.1.5. if there is a failure in the functioning of any other Service provided by the Company.',
      '11.2. The Website accepts no liability for any errors or omissions, on behalf of itself, or for any damage caused to you, your belongings, or any Third-Party, resulting from the use or misuse of the Platform or any Service provided of by the Company through the Platform. The Service and any Content or material displayed of the Services are provided without any guarantees, conditions, or warranties as to its accuracy, suitability, completeness, or reliability. We will not be liable to you for the unavailability or failure of the Platform.',
      '11.3. You are to comply with all Applicable Laws upon you or on your activities, and with all applicable policies, which are hereby incorporated into this Terms of Use by reference.',
      '11.4. The Platform expressly excludes any liability for any loss or damage that was not reasonably foreseeable by the Website and which is incurred by you in connection with the Website, including loss of profits; and any loss or damage incurred by you as a result of your breach of these Terms of Use.',
      '11.5. To the fullest extent permitted by law, We shall not be liable to You or any other party for any loss or damage, regardless of the form of action or basis of any claim. You acknowledge and agree that your sole and exclusive remedy for any dispute with us is to terminate your use of the Website.',
    ],
  },
  {
    title: '12. TERM',
    paras: [
      '12.1. These Terms of Use shall continue to form a valid and binding agreement between us and shall continue to be in full force and effect until you continue to access and use the Website.',
      '12.2. You may terminate your use of the Website at any time, as per the process specified under this Terms of Use.',
      '12.3. We may terminate these Terms of Use with you and suspend or terminate Your access to the Website at any time and for any reason if any discrepancy or legal issue arises.',
      '12.4. Such suspension or termination shall not limit our right to take any other action against you that we consider appropriate.',
      '12.5. It is also hereby declared that we may discontinue the Services on the Website without any prior notice.',
    ],
  },
  {
    title: '13. TERMINATION',
    paras: [
      '13.1. We reserve the right, in its sole discretion, to unilaterally terminate Your access to the Website, or any portion thereof, at any time, without notice or cause.',
      '13.2. We also reserve the universal right to deny access to You, to any/all of are on its Website without any prior notice/explanation to protect the interests of the Website and/or other Users to the Website.',
      '13.3. We reserve the right to limit, deny or create different access to the Website and its features concerning different Users, or to change any of the features or introduce new features without prior notice.',
      '13.4. You shall continue to be bound by these Terms of use, and it is expressly agreed to by You that You shall not have the right to terminate these Terms of Use till the expiry of the same.',
    ],
  },
  {
    title: '14. COMMUNICATION',
    paras: [
      'By using this Website and providing your identity and contact information to the Company through the Website, you agree and consent to receive e-mails or SMS from us and/or any of its representatives at any time.',
      'You can report to “info@cosmicvend.com” if you find any discrepancy with regard to Website or Content-related information and we will take necessary action after an investigation. The response with resolution (if any issues found) shall be dependent on the time is taken for investigation.',
      'You expressly agree that notwithstanding anything contained hereinabove, it may be contacted by us relating to any Services availed by you on the Website or anything pursuant thereto and you agree to indemnify us from any harassment claims. It is expressly agreed to by us that any information shared by us shall be governed by the Privacy Policy. By communicating with the Company through the Platform, submitting enquiries, or providing an email address or telephone number, the User consents to receive communications electronically, including by email, telephone, SMS, or other electronic means, for purposes relating to the User’s enquiry, customer support, service updates, or other legitimate business communications.',
    ],
  },
  {
    title: '15. USER OBLIGATIONS AND FORMAL UNDERTAKINGS AS TO CONDUCT',
    paras: [
      'You agree and acknowledges that you are a restricted user of this Platform and you:',
      '15.1. agree to provide genuine credentials during the process whenever required on the Website. You shall not use a fictitious identity. We are not liable if you have provided incorrect information;',
      '15.2. agree to ensure the Name, Email address, Phone Number, and any such other information that may be provided and is valid at all times and shall keep your information accurate and up-to-date;',
      '15.3. The User shall ensure that all information submitted through the Platform, including but not limited to enquiry forms, franchise applications, venue placement requests, or other communications, is true, accurate, complete, and up to date. The Company reserves the right, at its sole discretion, to refuse, suspend, disregard, or terminate the processing of any enquiry or communication where it reasonably believes that the information provided is false, misleading, incomplete, fraudulent, or otherwise in violation of these Terms of Use or Applicable Laws.',
      '15.4. authorize the Platform to use, store, or otherwise process certain personal information and all published Content, responses, locations, User comments, reviews, and ratings for personalization of Services, marketing, and promotional purposes, and for optimization of User-related options and Services;',
      '15.5. understand and agree that, to the fullest extent permissible by law, the Platform or any of their affiliates or their respective officers, directors, employees, agents, licensors, representatives, operational service providers, advertisers or suppliers shall not be liable for any loss or damage, of any kind, direct or indirect, in connection with or arising from the use of the Platform or this Terms of Use, including, but not limited to, compensatory, consequential, incidental, indirect, special or punitive damages;',
      '15.6. are bound not to cut, copy, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from, transfer, or sell any information or obtained from the Platform. Any such use/limited use of the Platform will only be allowed with the prior express written permission;',
      '15.7. agree not to access (or attempt to access) the Platform and/or the materials or Services by any means other than through the interface provided by the Platform. The use of deep-link, robot, spider or other automatic devices, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or its Content, or in any way reproduce or circumvent the navigational structure or presentation of the Platform, materials or any Content, or to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Platform will lead to suspension or termination of your access to the Platform. We disclaim any liabilities arising concerning such offensive Content on the Platform; and',
      '15.8. expressly agree and acknowledge that the Content generated by the Users and displayed on the Platform is not owned by the Company and that we are in no way responsible for the Content of the same. You may, however, report any offensive or objectionable content, which we may then remove from the Platform, at our sole discretion.',
      'You further undertake not to:',
      '15.9. engage in any activity that interferes with or disrupts access to the Platform or the Services provided therein (or the servers and networks which are connected to the Platform);',
      '15.10. impersonate any person or entity, or falsely state or otherwise misrepresent his/her affiliation with a person or entity;',
      '15.11. probe, scan, or test the vulnerability of the Platform or any network connected to the Platform, nor breach the security or authentication measures on the Platform or any network connected to the Platform. The User may not reverse look-up, trace, or seek to trace any information relating to any other User of, or visitor to the Platform, or any other viewer of the Platform, including any User account maintained on the Platform not operated/managed by the User, or exploit the Platform or information made available or offered by or through the Platform, in any manner;',
      '15.12. disrupt or interfere with the security of, or otherwise cause harm to the Platform, systems resources, accounts, passwords, servers, or networks connected to or accessible through the Platform or any affiliated or linked Platform;',
      '15.13. use the Platform or any material or Content therein for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Platform or any other Third-Party(ies);',
      '15.14. violate any code of conduct or guideline which may apply for or to any particular Service offered through the Platform;',
      '15.15. violate any applicable laws, rules, or regulations currently in force within or outside India;',
      '15.16. violate any portion of these Terms of Use or the Privacy Policy, including but not limited to any applicable additional terms and conditions of the Platform contained herein or elsewhere, whether made by amendment, modification, or otherwise;',
      '15.17. commit any act that causes the Company to lose (in whole or in part) the Services of its Internet Establishment (“ISP”) or in any manner disrupts the Services of any other supplier/service provider of the Platform;',
      '15.18. you hereby expressly authorize the Company to disclose any and all information relating to you in our possession to law enforcement or other government officials, as we may in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those involve personal injury and theft/infringement of intellectual property. You further understand that the Platform might be directed to disclose any information (including the identity of persons providing information or materials on the Platform) as necessary to satisfy any judicial order, Applicable Law, regulation or valid governmental request;',
      '15.19. by indicating your acceptance to use any Services offered through the Platform, you are obligated to complete such transactions after making payment. You shall be prohibited from indicating their acceptance to avail Services where the transactions have remained incomplete;',
      '15.20. you agree to use the Services provided by the Company, our affiliates, consultants and contracted companies, for lawful purposes only;',
      '15.21. you agree to provide authentic and true information. We reserve the right to confirm and validate the information and other details provided by you at any point in time. If upon Confirmation such details are found to be false, not to be true (wholly or partly), we shall in our sole discretion reject the order and debar you from using the Platform without prior intimation whatsoever;',
      '15.22. you agree not to post any material on the Platform that is defamatory, offensive, obscene, indecent, abusive, or needlessly distressful, or advertising any goods or services. More specifically, you agree not to host, display, upload, update, publish, modify, transmit, or in any manner share any information that:',
      '15.22.1. belongs to another person and to which you have no right to;',
      '15.22.2. is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;',
      '15.22.3. is in any way harmful to minors;',
      '15.22.4. infringes any patent, trademark, copyright or other proprietary rights;',
      '15.22.5. violates any Applicable Law for the time being in force;',
      '15.22.6. deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing;',
      '15.22.7. abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of others;',
      '15.22.8. impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;',
      '15.22.9. publish, post, disseminate, any grossly harmful information, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to “indecent representation of women” within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986; and',
      '15.22.10. threatens the unity, integrity, defence, security, or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.',
    ],
  },
  {
    title: '16. SUSPENSION OF USER ACCESS AND ACTIVITY',
    paras: [
      'Notwithstanding other legal remedies that may be available, we may in our sole discretion, limit your access and/or activity by immediately removing your access credentials either temporarily or indefinitely, or suspend/terminate your association with the Platform, and/or refuse to the usage of the Platform, without being required to provide you with notice or cause:',
      'a. if you are in breach of any of these Terms of Use, Privacy Policy, or any other applicable policies;',
      'b. if you have provided wrong, inaccurate, incomplete or incorrect information; and',
      'c. if your actions may cause any harm, damage or loss to the other Users or the Company, at our sole discretion.',
    ],
  },
  {
    title: '17. INTELLECTUAL PROPERTY RIGHTS',
    paras: [
      'Unless expressly agreed to in writing, nothing contained herein shall give you a right to use any of the trade names, trademarks, service marks, logos, domain names, information, questions, answers, solutions, reports, and other distinctive brand features, save according to the provisions of these Terms of Use that shall be available on the Platform. All logos, trademarks, brand names, service marks, domain names, including material, designs, and graphics created by and developed by either the Platform or such other Third-Party and other distinctive brand features of the Platform are the property of the Platform or the respective copyright or trademark owner. Furthermore, concerning the Platform, we shall be the exclusive owner of all the designs, graphics, and the like, related to the Platform.',
      'You shall not use any of the Intellectual Property displayed on the Platform in any manner that is likely to cause confusion among existing or prospective users of the Platform, or that in any manner disparages or discredits the Platform, to be determined in the sole discretion.',
      'You are aware all Intellectual Property, including but not limited to copyrights, relating to said Services resides with the owners, and that at no point does any such Intellectual Property stand transferred from the aforementioned creators.',
      'You are further aware that any reproduction or infringement of the Intellectual Property of the aforementioned owners by you will result in legal action being initiated against you by the respective owners of the Intellectual Property so reproduced/infringed upon. It is agreed to by you that the Contents of this section shall survive even after the termination or expiry of these Terms of Use and/or Privacy Policy.',
    ],
  },
  {
    title: '18. MEDIA USAGE',
    paras: [
      'The Company’s trademarks, logos, photographs, branding materials, press kits, and marketing assets may not be reproduced, published, distributed, or used for commercial purposes without the Company’s prior written consent, except where expressly authorised by the Company.',
    ],
  },
  {
    title: '19. RESERVATION OF RIGHTS',
    paras: [
      'The Company expressly reserves all rights not expressly granted under these Terms of Use. No licence, assignment, transfer, waiver, or other right in favour of any User shall arise by implication, estoppel, or otherwise.',
    ],
  },
  {
    title: '20. FORCE MAJEURE',
    paras: [
      'We will not be liable for damages for any delay or failure to perform our obligations hereunder if such delay or failure is due to cause beyond our control or without its fault or negligence, due to force majeure events including but not limited to acts of war, acts of God, earthquake, riot, fire, festive activities sabotage, labour shortage or dispute, internet interruption, technical failure, breakage of sea cable, hacking, piracy, cheating, illegal or unauthorized.',
    ],
  },
  {
    title: '21. DISPUTE RESOLUTION AND JURISDICTION',
    paras: [
      '21.1. These Terms shall be governed and interpreted by and construed in accordance with the substantive laws of India and subject to arbitration provisions below, each party hereby irrevocably and finally submits to the exclusive jurisdiction of the courts of Tiruvannamalai, Tamil Nadu, India thereto in respect of any disputes, legal action or proceedings arising out of or in connection with the Terms, interpretation, duties, performance, breach, etc. of these Terms.',
      '21.2. Should any Dispute arise out of or in connection with these Terms, the Parties hereto shall first endeavor to settle such Dispute amicably. If the Dispute is not resolved through amicable settlement within fifteen (15) days after commencement of discussions or such longer period as the Parties mutually agree in writing, then either Party may refer the Dispute for resolution by arbitration according to the provisions of the Arbitration and Conciliation Act, 1996 (India) or any statutory amendment or re-enactment thereof, or any statute enacted to replace the same, for the time being in force. The arbitration shall be conducted by a sole arbitrator appointed by mutual consent of the parties. The seat and venue of arbitration shall be in Tiruvannamalai, Tamil Nadu, India, and the language of the proceedings shall be English.',
      '21.3. The Award rendered in any arbitration commenced hereunder shall be final and conclusive, and judgment thereon may be entered in any court having jurisdiction for its enforcement. The Parties undertake to implement the arbitration award. In addition, the Parties agree that no Party shall have any right to commence or maintain a suit or legal proceeding concerning a Dispute hereunder (other than for preventive or interlocutory relief pending completion of the arbitration proceedings under these Terms) until the Dispute has been determined in accordance with the arbitration procedure provided for herein and then only for the enforcement of the award rendered in such arbitration. When any Dispute is under arbitration, except for the matters under dispute, the Parties shall continue to exercise their remaining respective rights and fulfil their remaining respective obligations under these Terms.',
    ],
  },
  {
    title: '22. MISCELLANEOUS PROVISIONS',
    paras: [
      '22.1. Entire Agreement: These Terms of Use, read with the Privacy Policy and Disclaimer form the complete and final contract between us with respect to the subject matter hereof and supersedes all other communications, representations, and agreements (whether oral, written, or otherwise) relating thereto.',
      '22.2. Waiver: The failure at any time to require the performance of any provision of these Terms of Use shall in no manner affect our right at a later time to enforce the same. No waiver by us of any breach of these Terms of Use, whether by conduct or otherwise, in any one or more instances, shall be deemed to be or construed as a further or continuing waiver of any such breach, or a waiver of any other breach of these Terms of Use.',
      '22.3. Severability: If any provision/clause of these Terms of Use is held to be invalid, illegal, or unenforceable by any court or authority of competent jurisdiction, the validity, legality, and enforceability of the remaining provisions/clauses of these Terms of Use shall in no way be affected or impaired thereby, and each such provision/clause of these Terms of Use shall be valid and enforceable to the fullest extent permitted by Applicable Law. In such case, these Terms of Use shall be reformed to the minimum extent necessary to correct any invalidity, illegality or unenforceability, while preserving to the maximum extent the original rights, intentions and commercial expectations of the Parties hereto, as expressed herein.',
      '22.4. Contact Us: If you have any questions about these Terms of Use, the practices of the Website, or your experience, you can contact us by emailing us at info@cosmicvend.com or by writing to us at :',
      'Hallow Essentials LLP',
      '57/18, Sattanayakan Street, Tiruvannamalai, Tamil Nadu – 606601, India',
      'Email: info@cosmicvend.com',
    ],
  },
]

/** A sub-heading line (e.g. "a) Definition", "7.1. General") gets slightly emphasised.
 *  Short, capitalised titles with no trailing punctuation — never list items. */
function isSubHeading(text: string): boolean {
  const t = text.trim()
  if (/[.;,]$/.test(t)) return false
  const letterTitle = /^[a-z]\)\s+[A-Z]/.test(t) && t.length <= 24
  const numberTitle = /^\d+\.\d+\.\s+[A-Z]/.test(t) && t.length <= 32
  return letterTitle || numberTitle
}

export default function TermsOfUsePage() {
  return (
    <div className="relative min-h-screen bg-[#07060F] overflow-x-hidden">
      <StarfieldCanvas />
      <Navbar />

      <article className="relative z-10 mx-auto max-w-4xl px-6 pt-36 pb-24">
        <p className="mb-3 font-mono text-xs uppercase tracking-[0.3em] text-[#C9A84C]">
          <span className="mr-2">&#10022;</span>Legal<span className="ml-2">&#10022;</span>
        </p>
        <h1 className="mb-3 font-serif text-4xl md:text-5xl text-[#F0EAFF]">Terms of Use</h1>
        <p className="font-sans text-sm text-[rgba(240,234,255,0.5)]">Posted as of 08-07-2026</p>
        <p className="mb-10 font-sans text-sm text-[rgba(240,234,255,0.5)]">
          Last updated as of 08-07-2026
        </p>

        <div className="mb-8 h-px w-full bg-linear-to-r from-transparent via-[#C9A84C]/30 to-transparent" />

        <h2 className="mb-5 font-serif text-2xl text-[#F0EAFF]">
          Welcome to CosmicVend’s Terms of Use
        </h2>
        {INTRO.map((p, i) => (
          <p
            key={`intro-${i}`}
            className="mb-4 font-sans text-[15px] leading-relaxed text-[rgba(240,234,255,0.72)]"
          >
            {p}
          </p>
        ))}

        {SECTIONS.map((section) => (
          <section key={section.title} className="mt-12">
            {section.title && (
              <h2 className="mb-5 font-serif text-2xl text-[#F0EAFF]">{section.title}</h2>
            )}
            {section.paras.map((p, i) =>
              isSubHeading(p) ? (
                <p
                  key={i}
                  className="mb-3 mt-6 font-mono text-sm uppercase tracking-wide text-[#C9A84C]"
                >
                  {p}
                </p>
              ) : (
                <p
                  key={i}
                  className="mb-4 font-sans text-[15px] leading-relaxed text-[rgba(240,234,255,0.72)]"
                >
                  {p}
                </p>
              ),
            )}
          </section>
        ))}
      </article>

      <Footer />
    </div>
  )
}
